version: '3'
services:
  frontend:
    build:
      context: ./
      dockerfile: /Dockerfile.frontend
    command: make run
    ports:
      - 3000:3000
    volumes:
      - ./apps/frontend ./
    working_dir: /usr/src
  backend:
    build:
      context: ./
      dockerfile: /Dockerfile.backend
    command: make run
    volumes:
      - ./apps/backend ./
    working_dir: /usr/src
